{{- if .Values.vault.enabled }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ include "kafka-lab.namespace" . }}
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault-secretstore
spec:
  provider:
    vault:
      server: {{ .Values.vault.address | quote }}
      path: {{ .Values.vault.kvPath | quote }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Values.vault.auth.role | quote }}
          serviceAccountRef:
            name: {{ .Values.vault.auth.serviceAccount }}
{{- end }}
